// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjBH2ptFqq4w5Ukzaze2MF9zcLzvU_vpI',
    appId: '1:593263418451:web:ea4af6db7f9665fa963aa6',
    messagingSenderId: '593263418451',
    projectId: 'iot-remote-access-828f0',
    authDomain: 'iot-remote-access-828f0.firebaseapp.com',
    storageBucket: 'iot-remote-access-828f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAhdHTWG4WUshCPMmKpkA5Kc6nMsTGPys',
    appId: '1:593263418451:android:c2dec0d231406068963aa6',
    messagingSenderId: '593263418451',
    projectId: 'iot-remote-access-828f0',
    storageBucket: 'iot-remote-access-828f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdwHx_NYI7Hyp9zyssTE9b9vUKlHX3L9w',
    appId: '1:593263418451:ios:1167614b584e5526963aa6',
    messagingSenderId: '593263418451',
    projectId: 'iot-remote-access-828f0',
    storageBucket: 'iot-remote-access-828f0.firebasestorage.app',
    iosBundleId: 'com.example.esp32',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdwHx_NYI7Hyp9zyssTE9b9vUKlHX3L9w',
    appId: '1:593263418451:ios:1167614b584e5526963aa6',
    messagingSenderId: '593263418451',
    projectId: 'iot-remote-access-828f0',
    storageBucket: 'iot-remote-access-828f0.firebasestorage.app',
    iosBundleId: 'com.example.esp32',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjBH2ptFqq4w5Ukzaze2MF9zcLzvU_vpI',
    appId: '1:593263418451:web:9b17c9f6e07e14d1963aa6',
    messagingSenderId: '593263418451',
    projectId: 'iot-remote-access-828f0',
    authDomain: 'iot-remote-access-828f0.firebaseapp.com',
    storageBucket: 'iot-remote-access-828f0.firebasestorage.app',
  );
}
